### PR TITLE
Making the SVG accessible

### PR DESCRIPTION
**Pull request by logan4473**
### Before :
149326268-7ad8fd64-8a92-4ca3-bf83-de20bc9d055e
### After : 👍 
fix

### CODE REVIEW

**Comment by palerdot** [comment]
This PR is missing some important things

- `aria-label` should be configurable via `svgAriaLabel` prop. The default value can be `React d3 speedometer`
- `focusable=false` is not added.

For adding props, it takes some involved change. Please go through the codebase for reference. If you are unsure, please reach out here. 

Also, please make sure you lint the code before committing. You can locally run `yarn lintfix` to fix your linting.

Also, please make sure tests are passing locally.

**Comment by palerdot** [comment]
@logan4473 Please refer to this comment on how this PR should be handled.

**Comment by logan4473** [comment]
All tests are passing locally.

**Comment by palerdot** [comment]
@logan4473 Please lint the code using `yarn lintfix` locally. CircleCi is failing - https://app.circleci.com/pipelines/github/palerdot/react-d3-speedometer/57/workflows/85fcb340-283d-4251-967a-96990d4f2f97/jobs/55

Please locally run `yarn test` and see if it passes. If not, please lint the code locally using `yarn lintfix` and make sure circleci tests passes.

**Comment by logan4473** [comment]
@palerdot I have already lint the code.
test
This is the yarn test result locally.

**Comment by palerdot** [comment]
@logan4473 Please check the PR comments and original instructions. There are things to be done in this PR like adding accessibility props to the end. 

I will check on the linting later.

**Comment by logan4473** [comment]
@palerdot  Can you please elaborate things to be done in this PR.

**Comment by palerdot** [comment]
> @palerdot Can you please elaborate things to be done in this PR.

@logan4473 

You have to add the `accessibility` props to the end so that it is easier to add all accessibility related props in the end.

Please read original instructions carefully and also spend some time on the PR comments.

**Comment by palerdot** [comment]
@logan4473 

I ran `yarn lintfix` in your PR. You have **not run lintfix** in your branch. Once you run this successfully, you will no longer see this diff https://github.com/palerdot/react-d3-speedometer/pull/136/files#diff-c3ff91a56981ae82bc04112746adb17a8ca558cb500aff0818da51aeb9cb4384 and the circle ci tests will pass.

Please make sure 
- run `yarn` first
- `yarn lintfix` (This will reset the changes for this file https://github.com/palerdot/react-d3-speedometer/pull/136/files#diff-c3ff91a56981ae82bc04112746adb17a8ca558cb500aff0818da51aeb9cb4384)

Once you push **circle ci tests will pass**.

I can consider this PR only after you **fix the linting and passes circle ci tests.**

**Comment by logan4473** [comment]
@palerdot

**Comment by palerdot** [comment]
@logan4473 

Tests are passing and the changes are looking ok. I'm merging this change into one of my branches, clean the commits, update the docs and prepare for release.

In future, please avoid one word commit messages and try to add descriptive commit messages.

Thank you for your time and effort in this issue.

You can follow the progress here - https://github.com/palerdot/react-d3-speedometer/pull/138

**Pull request merged**
